server:
  servlet:
    context-path: /ye
  port: 8080
spring:
  application:
    name: backend
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/backend?charcterEcoding=UTF-8&&serverTimezone=Asia/Shanghai
   username: root
   password: 123456
   type: com.alibaba.druid.pool.DruidDataSource   # 数据库连接池
   druid:
       initial-size: 5              # 初始化大小
       min-idle: 5                  # 最小连接数
       max-active: 20               # 最大连接数
       max-wait: 60000              # 获取连接时最大等待时间
       vaildation-query: SELECT 1   # 测试连接是否有效的SQL语句，为空时以下三个配置均无效
       test-on-borrow: true         # 申请连接时执行vaildationQuery检测连接是否有效，开启后会降低性能
       test-while-idle: true        # 申请连接时时如果空间时间超过min-evictable-idle-time-millis，执行vaildationQuery检测连接是否有效，开启后会降低性能
       test-on-return: true         # 归还连接时执行vaildationQuery检测连接是否有效，开启后会降低性能
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.backend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: api

mybatis-plus:
  configuration:
  # MyBatis Plus 配置 开启驼峰功能
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # MyBatis应用的实体类自定义别名
  type-aliases-package: com.example.backend.entity